/**
 * DAX measures data — AUTO-GENERATED by scripts/parse-dax-measures.js
 *
 * DO NOT EDIT MANUALLY.
 *
 * To regenerate:
 *   1. Add hemfrid_dax_measures.md to the repo root.
 *   2. Run: node scripts/parse-dax-measures.js
 *   3. Commit the updated _dax-data.ts.
 */

export interface DaxMeasure {
  title:          string;
  language:       string;
  code:           string;
  description:    string | null;
  subcategory_id: string;
  tags:           string[];
}

// Empty until parse-dax-measures.js is run.
export const DAX_MEASURES: DaxMeasure[] = [];
